import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../components/navbar";
import Footer from "../components/footer";
import { cookies } from 'next/headers';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "McApple",
  description: "Generated by Diego Gallo",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const token = cookies().get('token')?.value || null;
  const isLoggedIn = !!token;

  return (
    <html lang="en" className="h-full">
      <body className={`flex flex-col min-h-screen ${inter.className}`}>
        <Navbar isLoggedIn={isLoggedIn} />
        <main className="flex-grow">{children}</main>
        <Footer />
      </body>
    </html>
  );
}