import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../components/navbar";
import Footer from "../components/footer";
import { cookies } from 'next/headers';
import { CartProvider } from './context/CartContext';
import ChatbotComponent from '../components/Chatbot';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "McApple",
  description: "Generated by Diego Gallo",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  const token = cookies().get('token')?.value || null;
  const isLoggedIn = !!token;

  return (
    <html lang="en" className="h-full">
      <body className={`flex flex-col min-h-screen ${inter.className}`}>
        <CartProvider>
          <Navbar isLoggedIn={isLoggedIn} />
          <main className="flex-grow">{children}</main>
          <ChatbotComponent />
          <Footer />
        </CartProvider>
      </body>
    </html>
  );
}